"""add delete field on project

Revision ID: 6887c713b25f
Revises: d121a5ed0b3d
Create Date: 2025-10-02 11:44:31.759932

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6887c713b25f"
down_revision: str | None = "d121a5ed0b3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("is_deleted", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("project_latest", sa.Column("is_deleted", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_latest", "is_deleted")
    op.drop_column("project", "is_deleted")
    # ### end Alembic commands ###
