"""add new codex model

Revision ID: 73ef31902266
Revises: 7f7f3838aeea
Create Date: 2025-12-15 12:11:52.307570

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "73ef31902266"
down_revision: str | None = "7f7f3838aeea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
