"""add files to ChatInputUserMessages

Revision ID: 86f370b8e495
Revises: 6887c713b25f
Create Date: 2025-10-17 18:09:31.185080

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "86f370b8e495"
down_revision: str | None = "6887c713b25f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
