"""adding codex to configurations

Revision ID: 8b836c9b525b
Revises: d080fbbac7e4
Create Date: 2025-10-28 12:52:18.710840

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "8b836c9b525b"
down_revision: str | None = "d080fbbac7e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
