"""add is archiving

Revision ID: a2105381785a
Revises: 86f370b8e495
Create Date: 2025-10-09 18:16:48.274718

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2105381785a"
down_revision: str | None = "86f370b8e495"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("is_archiving", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("task_latest", sa.Column("is_archiving", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_latest", "is_archiving")
    op.drop_column("task", "is_archiving")
    # ### end Alembic commands ###
