"""seeing what the migration would do

Revision ID: d080fbbac7e4
Revises: a2105381785a
Create Date: 2025-10-22 14:59:38.301960

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "d080fbbac7e4"
down_revision: str | None = "a2105381785a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
