from __future__ import annotations

DEFAULT_CHECK_TIMEOUT_SECONDS = 10 * 60.0
AGENT_EXIT_CODE_CLEAN_SHUTDOWN_ON_INTERRUPT = 5
AGENT_EXIT_CODE_SHUTDOWN_DUE_TO_EXCEPTION = 6
AGENT_EXIT_CODE_FROM_SIGTERM = 143
AGENT_EXIT_CODE_FROM_SIGINT = 130
TMUX_OUTPUT_ARTIFACT_NAME = "tmux_output.txt"
