from pathlib import Path

import pytest
from playwright.sync_api import expect

from sculptor.testing.resources import IsolationLevel  # noqa: F401
from sculptor.testing.resources import auto_select_project_  # noqa: F401
from sculptor.testing.resources import container_prefix_  # noqa: F401
from sculptor.testing.resources import credentials_  # noqa: F401
from sculptor.testing.resources import database_url_  # noqa: F401
from sculptor.testing.resources import frontend_  # noqa: F401
from sculptor.testing.resources import local_sync_debounce_seconds_  # noqa: F401
from sculptor.testing.resources import multi_tab_page_factory_  # noqa: F401
from sculptor.testing.resources import pure_local_repo_  # noqa: F401
from sculptor.testing.resources import pure_local_repo_with_checks_  # noqa: F401
from sculptor.testing.resources import sculptor_backend_port_  # noqa: F401
from sculptor.testing.resources import sculptor_config_path_  # noqa: F401
from sculptor.testing.resources import sculptor_factory_  # noqa: F401
from sculptor.testing.resources import sculptor_folder_  # noqa: F401
from sculptor.testing.resources import sculptor_launch_mode_  # noqa: F401
from sculptor.testing.resources import sculptor_page_  # noqa: F401
from sculptor.testing.resources import snapshot_path_  # noqa: F401
from sculptor.testing.resources import test_repo_factory_  # noqa: F401
from sculptor.testing.resources import testing_mode_  # noqa: F401


@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {**browser_context_args, "viewport": {"width": 1600, "height": 1000}}


# This fixture depends on playwright's `output_path` fixture, we use it to
# record our artifacts and that way they sit next to videos and screenshots
# generated by playwright.
#
# It is important that it runs after the playwright's internal
# `_artifacts_recorder` so that we can actually see the files written by
# playwright. To achieve that, we use autouse as it's executed first.
# doc: https://docs.pytest.org/en/stable/reference/fixtures.html#autouse-fixtures-are-executed-first-within-their-scope
# FIXME: this breaks if we have any autouse fixtures that also depend on playwright's `page`, `context`, or `browser`!
#
# The `output_path` fixture is only generating a path and does nothing else so
# pulling it in should have no side effects.
@pytest.fixture(scope="function", autouse=True)
def record_generated_files(output_path: str, record_property):
    yield

    output = Path(output_path)
    if not output.exists():
        return

    # FIXME: make them all relative without hardcoding the path
    tests_cwd_path = Path.cwd()
    assert output.is_dir(), f"Expected output path to be a directory, got {output}"
    assert output.is_relative_to(tests_cwd_path), (
        f"Expected output path to be relative to {tests_cwd_path}, got {output}"
    )
    output = output.relative_to(tests_cwd_path)

    record_property("test_results_path", str(output) + "/")

    # TODO: should we namespace these properties with "imbue" or something similar?
    file_types = {
        "trace*.zip": "playwright_trace_path",  # hardcoded name coming from playwright's `_artifacts_recorder`
        "*.png": "image_path",
        "*.webm": "video_path",
    }
    for child in output.iterdir():
        if child.is_file():
            for pattern, file_type in file_types.items():
                if child.match(pattern):
                    record_property(f"{file_type}-{str(child.relative_to(output))}", str(child))
        elif child.is_dir():
            record_property(f"directory_path-{str(child.relative_to(output))}", str(child) + "/")


@pytest.fixture(autouse=True)
def configure_expect_timeout(is_updating_snapshots_: bool, testing_mode_: IsolationLevel) -> None:
    if is_updating_snapshots_ or testing_mode_ == IsolationLevel.NON_ISOLATED:
        expect.set_options(timeout=5 * 60 * 1000)
    else:
        expect.set_options(timeout=0.5 * 60 * 1000)
