import { Box, Flex, Text } from "@radix-ui/themes";
import { BoxIcon, GitCompareArrowsIcon } from "lucide-react";
import type { ReactElement } from "react";

import styles from "./SyncPopover.module.scss";

export const MergePanelPopoverTooltip = (): ReactElement => {
  return (
    <Flex direction="column" gap="3" p="5">
      <Text size="3" weight="medium">
        Merge Changes Quick Start
      </Text>

      <Flex direction="column" gap="3">
        <Box className={styles.gridItem}>
          <Box className={styles.popoverIconWrapper}>
            <BoxIcon size={16} />
          </Box>
          <Text size="2" weight="medium">
            Sculptor code lives in containers
          </Text>
          <Text size="1" color="gray">
            The code generated by Sculptor Agents lives in isolated containers. This keeps your local environment safe &
            unlocks simultaneous multi-branch, agentic work.
          </Text>
        </Box>

        <Box className={styles.gridItem}>
          <Box className={styles.popoverIconWrapper}>
            <GitCompareArrowsIcon size={16} />
          </Box>
          <Text size="2" weight="medium">
            Move code out of or into the Agent container with git operations
          </Text>
          <Box>
            <Text size="1" color="gray" as="div">
              <ul className={styles.popoverNumberedList}>
                <li>
                  <strong>Pull:</strong> sync code out of this Agent’s container into a branch in your local dev
                  environment
                </li>
                <li>
                  <strong>Push:</strong> sync code from your local dev environment into this Agent’s container
                </li>
              </ul>
            </Text>
          </Box>
        </Box>
      </Flex>
    </Flex>
  );
};
