#!/usr/bin/env python3
"""
A deterministic fake Codex agent that generates devcontainer files for the sample Python project.
This allows testing the Docker mechanics without LLM dependencies.

Usage: fake_codex_agent.py exec --sandbox danger-full-access --json PROMPT [--model MODEL]

Outputs Codex-style JSON events (item.started, item.completed, turn.completed).
"""

import argparse
import json
import sys
from pathlib import Path

# The devcontainer files to generate (following the format required by prompts.py)
DEVCONTAINER_JSON = """{
    "name": "Python Codex Test Environment",
    "build": {
        "dockerfile": "Dockerfile",
        "context": ".."
    }
}
"""

DOCKERFILE_TEMPLATE = """FROM python:3.12-slim
# Generated by fake_codex_agent.py (model: {model_label})

# Install uv for fast dependency management
RUN pip install uv

# Install dependencies that are unlikely to change
RUN apt-get update && apt-get install -y --no-install-recommends \\
    && rm -rf /var/lib/apt/lists/*

# Create test artifacts directory.
RUN mkdir -p /test_artifacts && chmod 777 /test_artifacts

# Copy source tree (excluding .devcontainer which changes frequently).
WORKDIR /project_src
COPY app.py ./
COPY tests/ ./tests/
COPY pyproject.toml ./

# Copy the test runner script last (changes frequently during development).
COPY .devcontainer/run_all_tests.sh /run_all_tests.sh
RUN chmod +x /run_all_tests.sh

# Install project dependencies
RUN uv pip install --system -e ".[dev]" || uv pip install --system pytest
"""

RUN_ALL_TESTS_SH = """#!/bin/bash
set -e

# Test artifacts are always written to /test_artifacts
TEST_ARTIFACT_DIR="/test_artifacts"
mkdir -p "$TEST_ARTIFACT_DIR/pytest"
mkdir -p "$TEST_ARTIFACT_DIR/junit"

# Run pytest with JUnit XML report
cd /project_src
python -m pytest tests/ \\
    --junitxml="$TEST_ARTIFACT_DIR/junit/pytest.xml" \\
    -v 2>&1 | tee "$TEST_ARTIFACT_DIR/pytest/stdout.txt"

PYTEST_EXIT_CODE=${PIPESTATUS[0]}

# Write final result
if [ $PYTEST_EXIT_CODE -eq 0 ]; then
    echo '{"success": true}' > "$TEST_ARTIFACT_DIR/final_result.json"
else
    echo '{"success": false}' > "$TEST_ARTIFACT_DIR/final_result.json"
fi

exit $PYTEST_EXIT_CODE
"""


def emit(event: dict) -> None:
    """Emit a JSON event to stdout (codex --json format)."""
    print(json.dumps(event), flush=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    # Codex CLI args: codex [--model MODEL] exec --sandbox danger-full-access --json PROMPT
    # --model is a global flag (before the subcommand) passed as --model=VALUE
    parser.add_argument("--model", type=str, default=None)
    parser.add_argument("command", nargs="?", default="exec", help="Subcommand (exec)")
    parser.add_argument("--sandbox", type=str, default="danger-full-access")
    parser.add_argument("--skip-git-repo-check", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("prompt", nargs="?", default="")
    # Use parse_known_args to be forward-compatible with new codex CLI flags
    args, _unknown = parser.parse_known_args()

    model_label = args.model or "unknown-model"
    print(
        f"fake_codex_agent.py built=2026-02-25T19:10 model={model_label}",
        file=sys.stderr,
        flush=True,
    )

    # Special model name triggers a simulated content filter rejection
    if model_label == "fake-error-model":
        emit({"type": "thread.started"})
        emit(
            {
                "type": "turn.failed",
                "error": {
                    "message": (
                        "Invalid prompt: your prompt was flagged as potentially "
                        "violating our usage policy. Please try again with a "
                        "different prompt: "
                        "https://platform.openai.com/docs/guides/reasoning#advice-on-prompting"
                    ),
                },
            }
        )
        print("Error: prompt rejected by content filter", file=sys.stderr, flush=True)
        sys.exit(1)

    # Create .devcontainer directory
    devcontainer_dir = Path(".devcontainer")
    devcontainer_dir.mkdir(exist_ok=True)

    # Write the files
    (devcontainer_dir / "devcontainer.json").write_text(DEVCONTAINER_JSON)
    (devcontainer_dir / "Dockerfile").write_text(
        DOCKERFILE_TEMPLATE.format(model_label=model_label)
    )
    run_script = devcontainer_dir / "run_all_tests.sh"
    run_script.write_text(RUN_ALL_TESTS_SH)
    run_script.chmod(0o755)

    # Output in codex --json format (NDJSON events)
    # Emit thread.started
    emit({"type": "thread.started"})

    # Emit agent messages with status markers as item events
    status_messages = [
        f"BOOTSTRAP_DEVCONTAINER_STATUS: [fake_codex_agent/{model_label}] Exploring repository structure.",
        f"BOOTSTRAP_DEVCONTAINER_STATUS: [fake_codex_agent/{model_label}] Creating devcontainer.json and Dockerfile.",
        f"BOOTSTRAP_DEVCONTAINER_STATUS: [fake_codex_agent/{model_label}] Completed setup of devcontainer files.",
        f"BOOTSTRAP_DEVCONTAINER_SUMMARY: [fake_codex_agent/{model_label}] Created Python devcontainer with pytest support.",
    ]

    for i, status in enumerate(status_messages):
        # item.started with agent_message
        emit(
            {
                "type": "item.started",
                "item": {
                    "type": "agent_message",
                    "text": status,
                    "id": f"msg_{i}",
                },
            }
        )
        # item.completed
        emit(
            {
                "type": "item.completed",
                "item": {
                    "type": "agent_message",
                    "text": status,
                    "id": f"msg_{i}",
                },
            }
        )

    # Emit file_change events for the files we created
    emit(
        {
            "type": "item.completed",
            "item": {
                "type": "file_change",
                "changes": [
                    {"path": ".devcontainer/devcontainer.json"},
                    {"path": ".devcontainer/Dockerfile"},
                    {"path": ".devcontainer/run_all_tests.sh"},
                ],
            },
        }
    )

    # Emit turn.completed with usage stats
    emit(
        {
            "type": "turn.completed",
            "usage": {
                "input_tokens": 0,
                "output_tokens": 0,
                "cached_input_tokens": 0,
            },
        }
    )


if __name__ == "__main__":
    main()
