#!/usr/bin/env python3
"""
A deterministic fake Claude agent that generates devcontainer files for the sample Python project.
This allows testing the Docker mechanics without LLM dependencies.

Usage: fake_claude_agent.py --dangerously-skip-permissions -p PROMPT --output-format stream-json --verbose [--model MODEL]
"""

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

# The devcontainer files to generate (following the format required by prompts.py)
DOCKERFILE_TEMPLATE = """FROM python:3.12-slim
# Generated by fake_claude_agent.py (model: {model_label})

# Install uv for fast dependency management
RUN pip install uv

# Install dependencies that are unlikely to change
RUN apt-get update && apt-get install -y --no-install-recommends \\
    && rm -rf /var/lib/apt/lists/*

# Create test artifacts directory.
RUN mkdir -p /test_artifacts && chmod 777 /test_artifacts

# Copy source tree (excluding .devcontainer which changes frequently).
WORKDIR /project_src
COPY app.py ./
COPY tests/ ./tests/
COPY pyproject.toml ./

# Copy the test runner script last (changes frequently during development).
COPY .devcontainer/run_all_tests.sh /run_all_tests.sh
RUN chmod +x /run_all_tests.sh

# Install project dependencies
RUN uv pip install --system -e ".[dev]" || uv pip install --system pytest
"""

RUN_ALL_TESTS_SH = """#!/bin/bash
set -e

# Test artifacts are always written to /test_artifacts
TEST_ARTIFACT_DIR="/test_artifacts"
mkdir -p "$TEST_ARTIFACT_DIR/pytest"
mkdir -p "$TEST_ARTIFACT_DIR/junit"

# Run pytest with JUnit XML report
cd /project_src
python -m pytest tests/ \\
    --junitxml="$TEST_ARTIFACT_DIR/junit/pytest.xml" \\
    -v 2>&1 | tee "$TEST_ARTIFACT_DIR/pytest/stdout.txt"

PYTEST_EXIT_CODE=${PIPESTATUS[0]}

# Write final result
if [ $PYTEST_EXIT_CODE -eq 0 ]; then
    echo '{"success": true}' > "$TEST_ARTIFACT_DIR/final_result.json"
else
    echo '{"success": false}' > "$TEST_ARTIFACT_DIR/final_result.json"
fi

exit $PYTEST_EXIT_CODE
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dangerously-skip-permissions", action="store_true")
    parser.add_argument("-p", "--prompt", type=str)
    parser.add_argument("--output-format", type=str)
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--max-budget-usd", type=float, default=1.0)
    parser.add_argument("--model", type=str, default=None)
    args = parser.parse_args()

    model_label = args.model or "unknown-model"

    # Create .devcontainer directory
    devcontainer_dir = Path(".devcontainer")
    devcontainer_dir.mkdir(exist_ok=True)

    # Copy the pre-generated devcontainer.json (provided by keystone at the project
    # root) into .devcontainer/.  This mirrors what a real agent should do — the
    # pre-generated file contains --network=host and cache settings that are
    # required for Docker builds on Modal.
    pregenerated = Path("devcontainer.json")
    assert pregenerated.exists(), (
        f"Pre-generated devcontainer.json not found in {Path.cwd()}. "
        "Keystone should place this file in the project root before running the agent."
    )
    shutil.copy2(pregenerated, devcontainer_dir / "devcontainer.json")
    (devcontainer_dir / "Dockerfile").write_text(
        DOCKERFILE_TEMPLATE.format(model_label=model_label)
    )
    run_script = devcontainer_dir / "run_all_tests.sh"
    run_script.write_text(RUN_ALL_TESTS_SH)
    run_script.chmod(0o755)

    # Output in stream-json format like claude does
    # First emit some status messages as an assistant would
    status_messages = [
        f"BOOTSTRAP_DEVCONTAINER_STATUS: [fake_claude_agent/{model_label}] Exploring repository structure.",
        f"BOOTSTRAP_DEVCONTAINER_STATUS: [fake_claude_agent/{model_label}] Creating devcontainer.json and Dockerfile.",
        f"BOOTSTRAP_DEVCONTAINER_STATUS: [fake_claude_agent/{model_label}] Completed setup of devcontainer files.",
        f"BOOTSTRAP_DEVCONTAINER_SUMMARY: [fake_claude_agent/{model_label}] Created Python devcontainer with pytest support.",
    ]

    for status in status_messages:
        assistant_msg = {
            "type": "assistant",
            "message": {"content": [{"type": "text", "text": status}]},
        }
        print(json.dumps(assistant_msg))

    # Run guardrail.sh to validate the generated files.
    # This ensures the guardrail script correctly validates agent output on modal.
    guardrail_path = Path("guardrail.sh")
    assert guardrail_path.exists(), f"guardrail.sh not found in {Path.cwd()}"

    guardrail_status = {
        "type": "assistant",
        "message": {
            "content": [
                {
                    "type": "text",
                    "text": f"BOOTSTRAP_DEVCONTAINER_STATUS: [fake_claude_agent/{model_label}] Running guardrail.sh self-check.",
                }
            ]
        },
    }
    print(json.dumps(guardrail_status))

    guardrail_result = subprocess.run(
        ["bash", str(guardrail_path)],
        stdout=sys.stderr,
    )

    if guardrail_result.returncode != 0:
        print(
            f"FATAL: guardrail.sh failed (exit {guardrail_result.returncode})",
            file=sys.stderr,
        )
        sys.exit(1)

    guardrail_pass_status = {
        "type": "assistant",
        "message": {
            "content": [
                {
                    "type": "text",
                    "text": f"BOOTSTRAP_DEVCONTAINER_STATUS: [fake_claude_agent/{model_label}] Guardrail self-check passed.",
                }
            ]
        },
    }
    print(json.dumps(guardrail_pass_status))

    result = {
        "type": "result",
        "usage": {
            "input_tokens": 0,
            "cache_read_input_tokens": 0,
            "output_tokens": 0,
        },
    }
    print(json.dumps(result))


if __name__ == "__main__":
    main()
