version: 0.1

log:
  level: info

storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]

# Required for buildx cache (large blobs)
compatibility:
  schema1:
    enabled: true
