version: 0.1

log:
  level: info

storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: 0.0.0.0:5000
  secret: keystone-registry-secret-v1
  relativeurls: true
  headers:
    X-Content-Type-Options: [nosniff]

auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
